xml_path: "{mujoco_workspace_dir}/../robots/wh044x/mjcf/wh044x_generated.xml"
chassis_build_dir: "{mujoco_workspace_dir}/../build"

simulation_dt: 0.001
control_decimation: 20  # 50Hz

num_actions: 8
num_obs: 8
num_obs_hist: 10

cmd_init: [0.0, 0.0, 0.0]
cmd_range: [1.0, 1.0, 2.0]
cmd_deadzone: [0.01, 0.01, 0.01]
